### ISSUE TITLE
Logging to `/tmp/lvm.log` without cleanup

### ISSUE THREAD

**Issue by spameier** [storaged-project/blivet#1155]
In [`lvm.py`](https://github.com/storaged-project/blivet/blob/5b1fcb11e89424974121a81613b6a6759d5ee8e1/blivet/devicelibs/lvm.py#L118C59-L118C59) the variable `config_string` is set to log at level 7 to `/tmp/lvm.log`. This leads to an ever growing log file in the `/tmp/` partition (example: https://lists.ovirt.org/archives/list/users@ovirt.org/message/MTRSJUUH6GXT7GSF46YK4PPW6G522DQ4/).

The behaviour was changed from debug only to always on in [29bae37](https://github.com/storaged-project/blivet/commit/29bae37592982e53baf281f778ba421bf61412e5#diff-3ccf915f204acabfb1e7a7f75def368956646d38f254f5818c571a81f1fab489L93-L94).

**Comment by vojtechtrefny** [comment]
Thank you for the report, the change definitely wasn't intentional, we'll change the logging back to debug only.
