### ISSUE TITLE
support separate thin pool metadata lvs

### ISSUE THREAD

**Issue by dwlehman** [storaged-project/blivet#18]
One very common model for setting up a thin pool is to create separate lvs for metadata and data. In this model, you create normal lvs and then turn them into a thin pool using lvconvert.

It is likely that there will be significant overlap in the implementation between this and support for cache lvs.

**Comment by vpodzime** [comment]
I think this is not worth holding off the 2.0 release. We have all the foundations ready now and adding support for this feature shouldn't need any API changes. Thus I think it can safely be moved to 2.1 or some other minor milestone.

**Comment by vojtechtrefny** [comment]
Fixed long time ago by #462
