### ISSUE TITLE
allow user-specified options to mkfs

### ISSUE THREAD

**Issue by dwlehman** [storaged-project/blivet#20]
This will work like the mountopts. That is, if the user specifies format options we do not use any of the defaults we normally use. The user/caller is responsible for making sure the options they provide are adequate.

It might be necessary to move some things around to make a coherent model that can accommodate both setup/mount options and create/mkfs options.

**Comment by vojtechtrefny** [comment]
Fixed long time ago by https://github.com/storaged-project/blivet/commit/68019e972e9577157270446d94d3a2dd2184bd20
