### ISSUE TITLE
Selection of LUKS hash algorithm

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/blivet#236]
Blivet does not allow to specify the hash algorithm that is used for LUKS volumes. This can create compliance issues as cryptsetup uses its default hash algorithm (SHA-1) if no hash algorithm is specified.

**Comment by vpodzime** [comment]
This first needs to be supported by libblockdev -- https://github.com/rhinstaller/libblockdev/issues/43

**Comment by bcl** [comment]
Seems like cryptsetup should be using something a bit more secure than SHA1 these days, shouldn't it?

**Comment by vpodzime** [comment]
Just adding a quote from [cryptsetup's FAQ *5. Security Aspects* section](https://gitlab.com/cryptsetup/cryptsetup/wikis/FrequentlyAskedQuestions#5-security-aspects):

>  5.20 LUKS is broken! It uses SHA-1!
> 
> No, it is not. SHA-1 is (academically) broken for finding collisions, but not for using it in a key-derivation function. And that collision vulnerability is for non-iterated use only. And you need the hash-value in verbatim.

> This basically means that if you already have a slot-key, and you have set the PBKDF2 iteration count to 1 (it is > 10'000 normally), you could (maybe) derive a different passphrase that gives you the the same slot-key. But if you have the slot-key, you can already unlock the key-slot and get the master key, breaking everything. So basically, this SHA-1 vulnerability allows you to open a LUKS container with high effort when you already have it open.

> The real problem here is people that do not understand crypto and claim things are broken just because some mechanism is used that has been broken for a specific different use. The way the mechanism is used matters very much. A hash that is broken for one use can be completely secure for other uses and here it is.

**Comment by bcl** [comment]
Well, ok. I can see their argument, but you'd think it wouldn't hurt to use something stronger.
