### ISSUE TITLE
Get rid of the ephemeral (py)parted objects

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/blivet#297]
The parted objects cause us many troubles (e.g. what's tracked in the PR #289) because they are not persistent and we never know if we are working with the current real values or some stale objects. It should be easy to get rid of those objects and use them only when reading and writing (committing) the data from/to disk. There's no point to use the (py)parted's objects to store some of the data with something being mirrored and something extra in our objects.

**Comment by vojtechtrefny** [comment]
This would definitely be nice, but I don't think we'll have capacity to do this change in near future, so I am closing this.
