### ISSUE TITLE
rename program.log to external.log

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/blivet#329]
Now that _libblockdev_ may use DBus for LVM instead of running binaries it may log DBus calls instead of information about spawning processes. Thus `external.log` is a more appropriate name than `program.log`.

**Comment by dwlehman** [comment]
I like it. This will also affect anaconda, right?

**Comment by vpodzime** [comment]
Unless we want to separate the blivet log from anaconda's log which is probably not a good idea.

**Comment by bcl** [comment]
I don't think this is the right thing to do. Leave spawned process logs in program.log and put the dbus logs into a new external.log or dbus.log or whatever. I don't really want to see program.log cluttered up with dbus stuff.

**Comment by vpodzime** [comment]
I don't see a big difference between spawning a process and doing a DBus call. Both are just asking for some actions or data by/from some external/standalone utility/process.
