### ISSUE TITLE
allow to set partition flags

### ISSUE THREAD

**Issue by alexanderlaw** [storaged-project/blivet#42]
With PartitionDevice I can't set partition flags such as bios_grub or hidden, that are supported by parted.
I can explicitly call partition.setFlag(parted.PARTITION_HIDDEN) for partition created, but then I should call partedDisk.commit() to get this flag saved. And after that I should inititate device rescanning.
I think it would be more appropriate, if flags could be set when creating a partition.

**Comment by dwlehman** [comment]
You should be able to call setFlag before committing the partition initially, eg:

```python

p = PartitionDevice(...)
p.setFlag(parted.PARTITION_HIDDEN)
doPartitioning(...)
devicetree.processActions()
```
However, if you use blivet to format the partition later it will probably unset the flag.

**Comment by dwlehman** [comment]
Can you provide a specific use-case for setting partition flags manually? (To provide motivation)
