### ISSUE TITLE
LV Creation doesn't work correctly.

### ISSUE THREAD

**Issue by wanginvc** [storaged-project/blivet#452]
Select disk1, disk2 as target storage.
case 1, disk1 with more than 500 MiB space left like 600 MiB, using LVMFactory to create LV on it with request size 1GiB, VG policy auto. Result is success.
case 2, disk1 with less than 500 MiB space left like 400 MiB, using LVMFactory to create LV on it with request size 396MiB, VG policy auto. Result is success.
case 3, disk1 with less than 500 MiB space left like 400 MiB, using LVMFactory to create LV on it with request size 1GiB, VG policy auto. Result is failure. Error message is "not enough free space for new device".
case 4, both disk1 and disk2 with 400 MiB, using LVMFactory to create LV on them with request size 500 MiB, VG policy auto. Result is failure. Error message is "not enough free space for new device".

Hints from codes in devicefactory.py: 
 984         # drop any new disks that don't have free space
 985         min_free = min(Size("500MiB"), self.parent_factory.size)
 986         add_disks = [d for d in add_disks if d.partitioned and
 987                                              d.format.free >= min_free]

If the candidate disks for new VG must be free space larger than 500 MiB, why not code like below:
 985         min_free = Size("500MiB")

The current codes logic depends greatly on self.parent_factory.size which is actually the request size of LVMFactory. I can't understand why.

**Comment by vpodzime** [comment]
@dwlehman, do you remember why you put 500 MiB there?

**Comment by dwlehman** [comment]
The minimum free space per disk of 500 MiB is fairly arbitrary. I suppose it could just as easily be 200 MiB. The reason we use the smaller of 500 MiB and the requested device's size is to allow requests for devices smaller than 500 MiB. What I really did not expect is people trying to use disks with such small amounts of free space.

**Comment by wanginvc** [comment]
For LV creating on single disk, if free space is less than 500 MiB, the request LV size must be less than or equal to free space. If free space is greater than 500 MiB, the request LV size can be less than or equal to or more than the free space. I can accept the different behavior above for single disk.

For LV creating on multiple disks, if free space of disk is less than 500 MiB, for example,  I have 5 disks with free space 400 MiB. If I want to take all free space to create LV with size 2 GiB on these disks with new VG created, It's not possible for blivet to handle this request. Blivet will complain that "not enough free space for new device". I expect blivet can handle above request successfully.

**Comment by dwlehman** [comment]
For creating such small LVs the best approach is to use `Blivet.new_partition`, `Blivet.new_vg`, `Blivet.new_lv` instead of the device factory. I would prefer to remain on the safe side than to spend a great deal of time trying to get really smart about how to know the smallest possible size.
