### ISSUE TITLE
TmpFSSize and unit tests

### ISSUE THREAD

**Issue by aszlig** [storaged-project/blivet#531]
While packing the latest release of blivet for NixOS I've stumbled on a few test errors. While some of these are certainly linked to Nix packaging, I'm not quite sure whether the failures regarding `test_resize`  of `ResizeTmpFSTestCase` are upstream bugs or some error with our packaging.

The full test log is here:

https://headcounter.org/hydra/log/89asli0s6nyc0h8x17layb4f0m72g24r-vm-test-run-blivet.drv

[Here](https://github.com/NixOS/nixpkgs/blob/ccbee460da2c875a04602c63e886b45fd11821da/pkgs/development/python-modules/blivet/default.nix) is the package itself and [here](https://github.com/NixOS/nixpkgs/blob/ccbee460da2c875a04602c63e886b45fd11821da/nixos/tests/blivet.nix) is how we run the test suite.

Now the tests return an error because during determining the file system size, the argument given to `df` is `None`. The argument in question is [`self.fs.system_mountpoint`](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/tasks/fssize.py#L133), which is generated using [`mounts_cache.get_mountpoints()`](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/formats/fs.py#L435-L436).

So far this makes sense, but if I'm looking into the code of [`MountsCache`](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/mounts.py#L85-L175) things are getting a bit confusing. In [`get_mountpoints()`](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/mounts.py#L95) there is a [branch](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/mounts.py#L116-L123) which only applies if devspec is not `None`, however with tmpfs it has the value `tmpfs`, so the branch actually applies.

This ends up trying to search for a [device](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/udev.py#L85-L118) while in reality if I'm correct there shouldn't be a device corresponding to a tmpfs. In the end it shouldn't even end up in the mentioned branch and just [`return self.mountpoints[(devspec, subvolspec)]`](https://github.com/rhinstaller/blivet/blob/blivet-2.1.7/blivet/mounts.py#L125), but that only would work if `devspec` is `None`.

So I'm confused on how this would work even on Fedora? Do you get the same errors while running the test suite? Or is there something wrong with my packaging?

**edit:** Fixed the URL to the test log.

**Comment by vojtechtrefny** [comment]
Hi, thank you for your report. #532 should fix this.

> This ends up trying to search for a device while in reality if I'm correct there shouldn't be a device corresponding to a tmpfs. In the end it shouldn't even end up in the mentioned branch and just return self.mountpoints[(devspec, subvolspec)], but that only would work if devspec is None.

Yes, that's right. I've changed the code to not to try looking for tmpfs "devices" in the udev database.

> So I'm confused on how this would work even on Fedora? Do you get the same errors while running the test suite? Or is there something wrong with my packaging?

I've checked our CI results and we are actually skipping these tests. Not sure why.

**Comment by aszlig** [comment]
> I've checked our CI results and we are actually skipping these tests. Not sure why.

Thanks a lot, that's what I wanted to know, so it's not an issue with Nix(OS).

@vojtechtrefny: Are the logs of the CI public, so I can easily verify other issues against the reference system?

**Comment by vojtechtrefny** [comment]
> @vojtechtrefny: Are the logs of the CI public, so I can easily verify other issues against the reference system?

Unfortunately not, the CI server is accessible only from local network. I've uploaded logs from last run to fpaste: https://paste.fedoraproject.org/518572/33694971/

**Comment by aszlig** [comment]
Thanks a lot. So from the test logs the reason these tests are not being run is because they require to be run as root user. Have you considered running these tests in a VM as we do as well?

**Comment by aszlig** [comment]
Speaking of this, I could also set up a Hydra (also a CI, but for Nix) jobset that's running the tests based on various branches of this project so we have a safety net for future releases until you have support for it in your CI. Would that help?

**Comment by vojtechtrefny** [comment]
> Thanks a lot. So from the test logs the reason these tests are not being run is because they require to be run as root user. Have you considered running these tests in a VM as we do as well?

I knew it's because we don't run the tests as root. I just don't know why -- we run the tests in VMs. Any idea @vpodzime ?

**Comment by vpodzime** [comment]
> Thanks a lot. So from the test logs the reason these tests are not being run is because they require to be run as root user. Have you considered running these tests in a VM as we do as well?
> 
> I knew it's because we don't run the tests as root. I just don't know why -- we run the tests in VMs. Any idea @vpodzime ?

I don't really know, we can probably just start running them.

**Comment by vpodzime** [comment]
> Speaking of this, I could also set up a Hydra (also a CI, but for Nix) jobset that's running the tests based on various branches of this project so we have a safety net for future releases until you have support for it in your CI. Would that help?

Any extra runs of the tests are definitely more than welcome. We are currently only covering Fedora Rawhide with the plan to also add the current Fedora stable release and RHEL 7. We also plan to make the results of CI runs public next week. But anything on top of that would be really great!

**Comment by vojtechtrefny** [comment]
I think we can close this now. The original issue with tests is fixed and we also started running the tests as root long time ago (even on multiple distributions and versions) and for PRs results are also public for some time now.
