### ISSUE TITLE
Blivet stays in endless loop when using pre-snapshots with clearpart

### ISSUE THREAD

**Issue by jkonecny12** [storaged-project/blivet#557]
I know this use-case is nonsense but we really shouldn't react by endless loop.

It stays in ``blivet/__init__.py: 834`` where it is waiting to clear all leaf devices but none of them are available, however all of this is in ``while devices:`` and removing of the device is in the ``for leaf in leafs:`` cycle, so when no `leafs` are available it will stays in this loop forever.

Hard to say what is the correct behavior (you can raise an exception or anything similar) but endless loop is always bad behavior.

It should be implement to rhel in this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1413942

**Comment by dwlehman** [comment]
I believe this was fixed by #563.
