### ISSUE TITLE
blivet-maint mailing list no longer working

### ISSUE THREAD

**Issue by puiterwijk** [storaged-project/blivet#561]
Fedora mail servers are unable to send emails to the maint list: <blivet-maint-list AT rh DOT c>: Recipient address rejected: Access denied.

Someone should check with the Red Hat mail team whether the list is still active.

**Comment by vojtechtrefny** [comment]
Sorry we ignored this for so long. blivet-maint is not really a mailing list, just a bug mail for our team and we are receiving the bug mails from bugzilla without problems so I'd say it works as expected. I'm not really sure who is responsible for this list maintenance, maybe @dwlehman knows.

I'm closing this issue, feel free to reopen it if you see the problem again.
