### ISSUE TITLE
release archives are unusable for rpm build

### ISSUE THREAD

**Issue by dwlehman** [storaged-project/blivet#6]
The archives are useless for several reasons. The release tagged blivet-0.61 has an associated archive with a top-level of blivet-blivet-0.61/. Also, there are no translations in the archive tarballs. It looks like we can add something to the Makefile to upload our own release tarballs to github -- see [here](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

Luckily this has not been a problem due to dist-git storing and using the tarballs we provide instead of grabbing Source0 from the spec file.

**Comment by vojtechtrefny** [comment]
When creating a [release](https://github.com/storaged-project/blivet/releases) here on GitHUB I manually upload the tarballs created by `make release` to the release, see for example the [3.4.2 release](https://github.com/storaged-project/blivet/releases/tag/blivet-3.4.2)  where the tarballs are available [here](https://github.com/storaged-project/blivet/releases/download/blivet-3.4.2/blivet-3.4.2-tests.tar.gz) and [here](https://github.com/storaged-project/blivet/releases/download/blivet-3.4.2/blivet-3.4.2-tests.tar.gz).

We might look into automating the GH release creation and tarball upload in the future, but we are currently making 4-5 releases a year so uploading the tarball manually isn't a huge issue.
