### ISSUE TITLE
[RFE] top level "supported filesystem formats" property

### ISSUE THREAD

**Issue by jcpunk** [storaged-project/blivet#673]
There is a `default_fstypes` property in `blivet.formats`.  It would be helpful if I could also query for a list of what types are actually supported.

https://github.com/storaged-project/blivet/blob/2.1-devel/blivet/formats/__init__.py#L64

**Comment by vojtechtrefny** [comment]
Anaconda uses this function to get list of supported filesystems -- https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/storage_utils.py#L928 -- so you could just copy it. But it's definitely good idea to implement it in blivet.
