### ISSUE TITLE
licensing issue

### ISSUE THREAD

**Issue by elasti-GuyT** [storaged-project/blivet#783]
Blivets' license is currently LGPLv2. However, it uses pyparted (for example: in partition.py there is an 'import parted' statement) which is GPLv2.
how can you have a lesser license (LGPLv2) if your'e using libraries with GPLv2 license?
thank you!

**Comment by vojtechtrefny** [comment]
Blivet license was changed from GPL to LGPL 6 ayers ago (see https://github.com/storaged-project/blivet/commit/70cbbff3806fc1755d9877154e327869868f30f8). I think @dwlehman didn't realize that PyParted is GPL only.
I guess the right thing to do is to switch the license back to GPL or possibly have two licenses and allow using some of the non partitioning-related code under LGPL.
Thank you for pointing this out and sorry for confusion.

**Comment by elasti-GuyT** [comment]
Thank you for your response
