### ISSUE TITLE
Add sleep before and/or after every action to avoid lvm timing problems?

### ISSUE THREAD

**Issue by dwlehman** [storaged-project/blivet#791]

**Comment by dwlehman** [comment]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1640601

**Comment by vpodzime** [comment]
> Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1640601

**You are not authorized to access bug #1640601. To see this bug, you must first log in to an account with the appropriate permissions.**

**Comment by vojtechtrefny** [comment]
It's our all time favourite:

> _ped.IOException: Partition(s) 3 on /dev/vda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.

**Comment by vpodzime** [comment]
That doesn't say anything about LVM.

**Comment by dwlehman** [comment]
We run pvremove on vda3, then try to remove vda3 0.25s later (despite two udev settle calls in between) and get the error. Something like 0.25s elapsed between the two operations. I thought I had seen something about a pvscan job being spawned somewhere, but I can't find it now.

Basically, I'm wondering if udev settle has become useless because of lvm scheduling asynchronous pvscan jobs. We get these bugs quite regularly and AFAIK they (almost?) always involve trying to manage partitions shortly after modifying an lvm device.

**Comment by vojtechtrefny** [comment]
I'm closing this now, the referenced bug is still not fixed, but it looks like it's not our problem and it's most likely not related to the pvremove and async pvscan -- we've added 5 second sleep after the pvremove operation and it still randomly fails and the issue sometimes occurs also on systems without existing LVM and only with partition-based intallation.
