### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [storaged-project/blivet#821]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
What weblate requires: a repository to interact with.
As you don't push po files in your repo, creating a dedicated repository for translations would make sense. Your automation would push the pot file to this dedicated repository so Weblate updates itself.

How do you push translations to users? In the distributed package? How often do you pull translations from Zanata?

**Comment by vojtechtrefny** [comment]
> [mandatory] which branch is your development branch?

We'll use a special repository with PO files for blivet -- https://github.com/storaged-project/blivet-weblate

> [mandatory] have you merged latest translation from Zanata and locked the project?

Yes, I've manually pushed PO files from Zanata and switch it to read-only.

> [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

We don't have a special license for the translations so if there isn't an existing licence from Zanata,  guess we'll use `LGPL-2.1-or-later` (same as code).

> [optional] do you need us to activate any specific checks? (this is a setting per component [3])

*python-format*, *python-brace-format*

> How do you push translations to users? In the distributed package? How often do you pull translations from Zanata?

We pull the translations from Zanata for every release and we distribute them in the source tarball.

**Comment by Jibec** [comment]
thank you for starting this.

Please:

- add a COPYING as source code so license is explicit.
- allow @weblate to have commit access
- connect once to https://translate.fedoraproject.org and tell me your username so I can add you as admin

**Comment by vojtechtrefny** [comment]
> add a COPYING as source code so license is explicit.
> allow @weblate to have commit access

Done.

> connect once to https://translate.fedoraproject.org and tell me your username so I can add you as admin

vtrefny

**Comment by Jibec** [comment]
Thank you.
Configuration is done and you are admin.

Please reach the translation mailing list for questions: 
https://lists.fedoraproject.org/archives/list/trans@lists.fedoraproject.org/
Or open a ticket in https://pagure.io/fedora-l10n/tickets

Weblate will push commits to the repository and synchronize po files 
each time a pot file is update.
If you wish to add new branches, please do it in copying the 
configuration done for the "master" component (both in settings and 
add-ons).

Thanks for your help

**Comment by vojtechtrefny** [comment]
I believe this can be closed now, our migration to weblate should be finished.
