### ISSUE TITLE
Add support for parsing the file `/etc/fstab`

### ISSUE THREAD

**Issue by poncovka** [storaged-project/blivet#828]
Anaconda currently uses two ways of parsing `/etc/fstab`: the function called `_parse_fstab` [0] and the method `parse_fstab` of the class `FSSet` [1]. I wanted to merge them into one, but @vojtechtrefny told me, that Blivet plans to add support for parsing the file `/etc/fstab`. We would be happy to use it in Anaconda and drop our current implementations. 

[0] https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/storage/root.py#L252
[1] https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/storage/fsset.py#L401

**Comment by vojtechtrefny** [comment]
Note that storage role also supports some basic fstab manipulation so it also a candidate to use this functionality from blivet. We might also consider using [UDisks](http://storaged.org/doc/udisks2-api/2.9.4/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.Configuration) which provides DBus API for fstab management which might be better than writing something from scratch (but even if we decide to use it, we'll still need a wrapper in blivet).

**Comment by tbzatek** [comment]
...or move the fstab management routines from udisks to libblockdev (for the 3.0 release)?

**Comment by japokorn** [comment]
Links in the description are no longer valid. Updated values are:
[0] [https://github.com/rhinstaller/anaconda/blob/b86bf41fcd3b51cf7c9809331656d7a7762e2851/pyanaconda/modules/storage/devicetree/root.py#L248](https://github.com/rhinstaller/anaconda/blob/b86bf41fcd3b51cf7c9809331656d7a7762e2851/pyanaconda/modules/storage/devicetree/root.py#L248)
[1] [https://github.com/rhinstaller/anaconda/blob/b86bf41fcd3b51cf7c9809331656d7a7762e2851/pyanaconda/modules/storage/devicetree/fsset.py#L441](https://github.com/rhinstaller/anaconda/blob/b86bf41fcd3b51cf7c9809331656d7a7762e2851/pyanaconda/modules/storage/devicetree/fsset.py#L441)

**Comment by vojtechtrefny** [comment]
WIP fstab management by @dwlehman which uses libmount Python API: https://github.com/dwlehman/blivet/commit/ca07d68385870f532994b3460475651ed29deb7a

I think you should start by gathering the requirements from Anaconda and storage role and design Blivet API, what will be used as a "backend" isn't that important as it can be changed later. Starting with the Anaconda code which might not be perfect, but works is probably the best start (if it wouldn't require bigger changes) and we can later decide whether to use libmount or UDisks or something else (libblockdev?).

**Comment by vojtechtrefny** [comment]
Note that we are also getting requests to allow specifying what type of device identifier will be used in fstab, so the API might need to reflect that too. We currently have the `fstab_spec` property in blivet which specifies to use either UUID or device path (for LVM devices or if UUID is not known for some reason), but we already have requests to use UUID all the time and also one to prefer filesystem label over UUID, so option to set this globally would be nice.

**Comment by vojtechtrefny** [comment]
Closed via #1119
