### ISSUE TITLE
Please consider publishing on PyPI

### ISSUE THREAD

**Issue by dtantsur** [storaged-project/blivet#858]
Hi folks!

We in ironic [1] are looking for a library to manage advanced partitioning library, and blivet looks a great choice. However, we need to support non-Red Hat systems and we need to support installation in virtual environments. Would it be possible to publish blivet to PyPI so that we can `pip install` it?

[1] https://docs.openstack.org/ironic/

**Comment by vojtechtrefny** [comment]
Hi, I'm not against adding blivet to PyPI in general, but I'm not sure if it really helps. We use [libblockdev](https://github.com/storaged-project/libblockdev) for most of the low level storage configuration and libblockdev is a C library (with Python bindings) so it can't be installed from PyPI. libblockdev is available for most distributions from standard repositories so it isn't hard to install but it means there is an extra non trivial installation step.

Adding blivet to PyPi should be relatively easy, it can be already installed with pip from our git using existing `setup.py` so it should work for PyPI too. So if the dependency on libblockdev isn't a problem for you, we can definitely add blivet to PyPI.

**Comment by dtantsur** [comment]
> libblockdev is a C library (with Python bindings) so it can't be installed from PyPI. libblockdev is available for most distributions from standard repositories so it isn't hard to install but it means there is an extra non trivial installation step.

This doesn't pose any problems for us, we're already installing similar dependencies like libffi-devel, libssl-devel, postgresql-devel and so on. It seems to be a relatively common pattern in the Python world. I think a README note on this requirement is enough.

> we can definitely add blivet to PyPI.

Would be amazing, thanks for your response!

**Comment by vojtechtrefny** [comment]
I've merged the changes needed for blivet to work with pypi and I plan to do the pypi build later today or tomorrow. Blivet on test PyPI: https://test.pypi.org/project/blivet/

**Comment by vojtechtrefny** [comment]
Blivet on PyPI: https://pypi.org/project/blivet/

**Comment by dtantsur** [comment]
Thanks!
