### ISSUE TITLE
Unable to import blivet with "minimal dependencies"

### ISSUE THREAD

**Issue by RaitoBezarius** [storaged-project/blivet#894]
I am trying to package the latest version of `blivet` for NixOS in order to use it with <https://github.com/NixOS/nixpart> ; but I'm running in a lot of issues and I'm not really accustomed to the whole project.

As far as I understand it, this project requires:
-  libblockdev
- pykickstart
- pyparted
- pyudev
- libselinux
 - pygobject3
- six

What I don't understand is especially, how versions are locked for these dependencies.
But, even if I try to bump everything to their latest version, I'm running in the following issue:

`ValueError: Namespace BlockDev not available` related to GObject, so I can only guess it is due to `libblockdev`, but unsure why.
I can only infer that GObject has some automatic discovery somewhere, it would be interesting to know how/why.

Do you have any idea regarding all those points?

Thanks in advance :)

**Comment by vojtechtrefny** [comment]
>     * pykickstart

Pykickstart is no longer needed, we've removed this dependency in 3.0 (together with moving installer-specific code to Anaconda).

You are also missing [libbytesize](https://github.com/storaged-project/libbytesize) and its python bindings.

> 
> `ValueError: Namespace BlockDev not available` related to GObject, so I can only guess it is due to `libblockdev`, but unsure why.
> I can only infer that GObject has some automatic discovery somewhere, it would be interesting to know how/why.
> 

libblockdev is a C library and we use [GObject Introspection](https://gi.readthedocs.io/en/latest/) to build Python bindings for it. The `ValueError` you see mean GI can't find the typelib file for libblockdev (`BlockDev.typelib`). On Fedora it is located in `/usr/lib64/girepository-1.0/BlockDev-2.0.typelib` and we ship it in the libblockdev package but on some distributions (like Debian) typelib files are shipped in separate packages (`gir1.2-blockdev-2.0` for Debian). I'm not sure how packaging on NixOS works, I hope this helps.

Also make sure you have the `BlockDev.py` file with GI overrides (in Fedora this in the standard Python `site-packages` folder, e.g. `/usr/lib64/python3.8/site-packages/gi/overrides/BlockDev.py` and in a separate `python3-blockdev` package).

**Comment by vojtechtrefny** [comment]
@RaitoBezarius  were you able to get this working? Is there something else we can help you with or can we close this issue?

**Comment by vojtechtrefny** [comment]
I assume you were able to fix the issue and I'm closing this now, feel free to reopen the issue or report a new one if you need additional help.

**Comment by RaitoBezarius** [comment]
Hi Vojtech, thanks for your message. Indeed, I had a working version at
some point so it is fine, thanks a lot!
