### ISSUE TITLE
Build without SElinux python module

### ISSUE THREAD

**Issue by karthikprabhu17** [storaged-project/blivet#928]
I am trying to build this for another linux other than fedora, centos, debian etc. Problem is that it does not support SELinux. Is there a way to build blivet without the selinux python module?

**Comment by karthikprabhu17** [comment]
will setting to false work

https://github.com/storaged-project/blivet.git

**Comment by vojtechtrefny** [comment]
Setting the SELinux flag to `False` with some minor tweaks should do the trick, check #929, I tested it with both SELinux disabled and enabled and with `python3-libselinux` uninstalled on Fedora, but it would be nice to test it on system where SELinux is not installed to be sure.

**Comment by karthikprabhu17** [comment]
I just tried your patch. It worked. We can close. Thank you very much.
