### ISSUE TITLE
Replace uses of IOError

### ISSUE THREAD

**Issue by VladimirSlavik** [storaged-project/blivet#944]
`IOError` has been deprecated a long time ago, it is now an alias for `OSError`. Blivet generally contains two kinds uses:

1. Guarding against failures of file access (`open`, `read` etc.). These can be just replaced with `OSError`.
2. It raises it in several places. These need replacing with something else.

See also https://github.com/rhinstaller/anaconda/pull/3239

**Comment by vojtechtrefny** [comment]
Closing the issue, both #946 and #990 are now merged and there are no more `IOError`s in blivet.
